#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleObjCInetFoundation-import-private.h
src/reflect/_MulleObjCInetFoundation-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleObjCInetFoundation-import.h
src/reflect/_MulleObjCInetFoundation-include.h
)

set( PUBLIC_HEADERS
src/MulleObjCInetFoundation.h
src/MulleObjCLoader+MulleObjCInetFoundation.h
src/NSCharacterSet+MulleURL.h
src/NSHost.h
src/NSMutableCharacterSet+MulleURL.h
src/NSURL.h
src/import.h
src/include.h
)

