#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleObjCInetFoundation.m
src/NSCharacterSet+MulleURL.m
src/NSHost.m
src/NSMutableCharacterSet+MulleURL.m
src/NSString+MulleURL.m
src/NSURL+File.m
src/NSURL.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCInetFoundation.m
)
