# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/MulleObjCInetFoundation.m
src/NSCharacterSet+MulleURL.m
src/NSHost.m
src/NSMutableCharacterSet+MulleURL.m
src/NSString+MulleURL.m
src/NSURL+File.m
src/NSURL.m
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCInetFoundation.m
)
