/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE_OBJC_LOCK_FOUNDATION_VERSION)
# if MULLE_OBJC_LOCK_FOUNDATION_VERSION < ((0 << 20) | (20 << 8) | 1)
#  error "MulleObjCLockFoundation is too old"
# endif
# if MULLE_OBJC_LOCK_FOUNDATION_VERSION >= ((0 << 20) | (21 << 8) | 0)
#  error "MulleObjCLockFoundation is too new"
# endif
#endif

#if defined( MULLE_OBJC_STANDARD_FOUNDATION_VERSION)
# if MULLE_OBJC_STANDARD_FOUNDATION_VERSION < ((0 << 20) | (20 << 8) | 1)
#  error "MulleObjCStandardFoundation is too old"
# endif
# if MULLE_OBJC_STANDARD_FOUNDATION_VERSION >= ((0 << 20) | (21 << 8) | 0)
#  error "MulleObjCStandardFoundation is too new"
# endif
#endif

#if defined( MULLE_URL_VERSION)
# if MULLE_URL_VERSION < ((2 << 20) | (3 << 8) | 4)
#  error "mulle-url is too old"
# endif
# if MULLE_URL_VERSION >= ((3 << 20) | (0 << 8) | 0)
#  error "mulle-url is too new"
# endif
#endif
