/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _MulleObjCInetFoundation_include_h__
#define _MulleObjCInetFoundation_include_h__

// How to tweak the following mulle-url #include
//    remove:             `mulle-sourcetree mark mulle-url no-header`
//    rename:             `mulle-sde dependency|library set mulle-url include whatever.h`
//    toggle #import:     `mulle-sourcetree mark mulle-url [no-]import`
//    toggle localheader: `mulle-sourcetree mark mulle-url [no-]localheader`
//    toggle public:      `mulle-sourcetree mark mulle-url [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-url [no-]require`
//    remove for os:      `mulle-sourcetree mark mulle-url no-os-<osname>`
# if defined( __has_include) && __has_include("mulle-url.h")
#   include "mulle-url.h"   // mulle-url
# else
#   include <mulle-url/mulle-url.h>   // mulle-url
# endif

#endif
