/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 2231393C-0D62-44C6-B581-C3AF1DF78321 instead of MulleObjCStandardFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCStandardFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCStandardFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCStandardFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCStandardFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCStandardFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCStandardFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCStandardFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCStandardFoundation/MulleObjCStandardFoundation.h>   // MulleObjCStandardFoundation

// You can tweak the following #import with these commands.
// (Use DEAC2607-B1D1-43A7-928D-926A2ADB1AF3 instead of MulleObjCLockFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCLockFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCLockFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCLockFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCLockFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCLockFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCLockFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCLockFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCLockFoundation/MulleObjCLockFoundation.h>   // MulleObjCLockFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCInetFoundation-include.h")
#  include "_MulleObjCInetFoundation-include.h"
# endif
#endif

