      { @selector( MulleObjCLoader), @selector( MulleFoundationBase) },      // 47a9beb6;MulleObjCLoader;efab19ea;MulleFoundationBase
      { @selector( NSCharacterSet), @selector( MulleURL) },      // bb258d72;NSCharacterSet;cd22f47a;MulleURL
      { @selector( NSHost), MULLE_OBJC_NO_CATEGORYID },      // fe455508;NSHost;;
      { @selector( NSMutableCharacterSet), @selector( MulleURL) },      // a5cef654;NSMutableCharacterSet;cd22f47a;MulleURL
      { @selector( NSString), @selector( MulleURL) },      // 1994a171;NSString;cd22f47a;MulleURL
      { @selector( NSString), @selector( NSHost) },      // 1994a171;NSString;fe455508;NSHost
      { @selector( NSURL), @selector( File) },      // 6b1e8f73;NSURL;b1836632;File
      { @selector( NSURL), MULLE_OBJC_NO_CATEGORYID },      // 6b1e8f73;NSURL;;
