      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 58bd58d3;MulleObjCLoader;efe3d73e;MulleObjCStandardFoundation
      { @selector( NSHost), MULLE_OBJC_NO_CATEGORYID },      // 324806f6;NSHost;;
      { @selector( NSString), @selector( NSHost) },      // 85e3fa43;NSString;324806f6;NSHost
      { @selector( NSURL), MULLE_OBJC_NO_CATEGORYID },      // b15f7adb;NSURL;;
