      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( NSHost), MULLE_OBJC_NO_CATEGORYID },      // fe455508;NSHost;;
      { @selector( NSString), @selector( MulleHTMLEscaping) },      // 1994a171;NSString;721b13f4;MulleHTMLEscaping
      { @selector( NSString), @selector( NSHost) },      // 1994a171;NSString;fe455508;NSHost
      { @selector( NSURL), @selector( File) },      // 6b1e8f73;NSURL;b1836632;File
      { @selector( NSURL), @selector( HTTP) },      // 6b1e8f73;NSURL;6b67da50;HTTP
      { @selector( NSURL), MULLE_OBJC_NO_CATEGORYID },      // 6b1e8f73;NSURL;;
