      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( NSHost), MULLE_OBJC_NO_CATEGORYID },      // fe455508;NSHost;;
      { @selector( NSString), @selector( NSHost) },      // 1994a171;NSString;fe455508;NSHost
      { @selector( NSURL), MULLE_OBJC_NO_CATEGORYID },      // 6b1e8f73;NSURL;;
