#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleObjCInetFoundation.c
src/NSHost.m
src/NSURL.m
src/http_parser.c
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCInetFoundation.m
)

set( STANDALONE_SOURCES
src/MulleObjCInetFoundationStandalone.m
src/MulleObjCInetFoundation-standalone.m
)
